#!/usr/bin/env python3
"""Generate compact Unicode grapheme-property tables for the C++ text core.

This is a maintainer tool. The generated header is committed, so consumers do
not need Python or the regex package. Regenerate with a recent regex release
when the project's Unicode version is advanced.
"""

from pathlib import Path
import regex


MAX_CODEPOINT = 0x110000
GCB_PROPERTIES = (
    "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
    "Prepend", "SpacingMark", "L", "V", "T",
)
EXTRA_PROPERTIES = (
    ("ExtendedPictographic", "Extended_Pictographic"),
    ("EmojiPresentation", "Emoji_Presentation"),
    ("InCbConsonant", "InCB=Consonant"),
    ("InCbExtend", "InCB=Extend"),
    ("InCbLinker", "InCB=Linker"),
)


def property_ranges(expression: str):
    pattern = regex.compile(rf"\A\p{{{expression}}}\Z")
    ranges = []
    start = previous = None
    for codepoint in range(MAX_CODEPOINT):
        if pattern.match(chr(codepoint)) is None:
            continue
        if start is None:
            start = previous = codepoint
        elif codepoint == previous + 1:
            previous = codepoint
        else:
            ranges.append((start, previous))
            start = previous = codepoint
    if start is not None:
        ranges.append((start, previous))
    return ranges


def format_range(first: int, last: int, suffix: str = "") -> str:
    return f"    {{0x{first:06X}, 0x{last:06X}{suffix}}},"


def main():
    gcb_ranges = []
    for name in GCB_PROPERTIES:
        expression = f"gcb={name}"
        enum_name = name.replace("Regional_Indicator", "RegionalIndicator")
        for first, last in property_ranges(expression):
            gcb_ranges.append((first, last, enum_name))
    gcb_ranges.sort()

    extras = [(name, property_ranges(expression)) for name, expression in EXTRA_PROPERTIES]
    output = [
        "#pragma once",
        "",
        "// Generated by scripts/generate_grapheme_break_data.py.",
        f"// Property source: Python regex {regex.__version__} Unicode property database.",
        "",
        "#include <cstdint>",
        "",
        "namespace wsc::text::grapheme_data {",
        "",
        "enum class BreakProperty : std::uint8_t",
        "{",
        "    Other, CR, LF, Control, Extend, ZWJ, RegionalIndicator,",
        "    Prepend, SpacingMark, L, V, T, LV, LVT",
        "};",
        "",
        "struct PropertyRange",
        "{",
        "    std::uint32_t first;",
        "    std::uint32_t last;",
        "    BreakProperty property;",
        "};",
        "",
        "inline constexpr PropertyRange kBreakPropertyRanges[] = {",
    ]
    output.extend(format_range(first, last, f", BreakProperty::{name}")
                  for first, last, name in gcb_ranges)
    output.extend([
        "};",
        "",
        "struct CodepointRange",
        "{",
        "    std::uint32_t first;",
        "    std::uint32_t last;",
        "};",
    ])
    for name, ranges in extras:
        output.extend(["", f"inline constexpr CodepointRange k{name}Ranges[] = {{"])
        output.extend(format_range(first, last) for first, last in ranges)
        output.append("};")
    output.extend(["", "} // namespace wsc::text::grapheme_data", ""])

    destination = Path(__file__).resolve().parents[1] / "src" / "text" / "GraphemeBreakData.h"
    destination.write_text("\n".join(output), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
