@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
for %%I in ("%SCRIPT_DIR%\..") do set "ROOT_DIR=%%~fI"

set "CONFIG=Release"
set "PACKAGE_DIR=%ROOT_DIR%\out\package\%CONFIG%"
set "CONSUMER_BUILD_DIR=%ROOT_DIR%\build-package-consumer"
set "GENERATOR="
set "GENERATOR_IS_MULTI_CONFIG=1"
set "MAKE_PROGRAM="
set "CXX_COMPILER="
set "RC_COMPILER="
set "MT_PROGRAM="

if defined WHATSCANVAS_PACKAGE_CONFIG set "CONFIG=%WHATSCANVAS_PACKAGE_CONFIG%"
if defined WHATSCANVAS_PACKAGE_DIR set "PACKAGE_DIR=%WHATSCANVAS_PACKAGE_DIR%"
if defined WHATSCANVAS_CONSUMER_BUILD_DIR set "CONSUMER_BUILD_DIR=%WHATSCANVAS_CONSUMER_BUILD_DIR%"
set "SOFTWARE_CONSUMER_BUILD_DIR=%CONSUMER_BUILD_DIR%-software"
if defined WHATSCANVAS_CONSUMER_GENERATOR set "GENERATOR=%WHATSCANVAS_CONSUMER_GENERATOR%"
if defined WHATSCANVAS_CONSUMER_MULTI_CONFIG set "GENERATOR_IS_MULTI_CONFIG=%WHATSCANVAS_CONSUMER_MULTI_CONFIG%"
if defined WHATSCANVAS_CONSUMER_MAKE_PROGRAM set "MAKE_PROGRAM=%WHATSCANVAS_CONSUMER_MAKE_PROGRAM%"
if defined WHATSCANVAS_CONSUMER_CXX_COMPILER set "CXX_COMPILER=%WHATSCANVAS_CONSUMER_CXX_COMPILER%"
if defined WHATSCANVAS_CONSUMER_RC_COMPILER set "RC_COMPILER=%WHATSCANVAS_CONSUMER_RC_COMPILER%"
if defined WHATSCANVAS_CONSUMER_MT set "MT_PROGRAM=%WHATSCANVAS_CONSUMER_MT%"

if /I "%GENERATOR%"=="Ninja" set "GENERATOR_IS_MULTI_CONFIG=0"
if /I "%GENERATOR%"=="NMake Makefiles" set "GENERATOR_IS_MULTI_CONFIG=0"
if /I "%GENERATOR%"=="Unix Makefiles" set "GENERATOR_IS_MULTI_CONFIG=0"

python "%ROOT_DIR%\scripts\verify_desktop_release_artifact.py" --package-dir "%PACKAGE_DIR%" >nul 2>&1
if errorlevel 1 (
    echo Current package not found or stale, building it first: "%PACKAGE_DIR%"
    call "%ROOT_DIR%\build.bat" --release --package --no-run
    if errorlevel 1 (
        echo PACKAGE_CONSUMER_SMOKE_RESULT=FAIL
        echo PACKAGE_CONSUMER_SMOKE_FAILED_STAGE=PACKAGE
        exit /b 1
    )
)

python "%ROOT_DIR%\scripts\verify_desktop_release_artifact.py" --package-dir "%PACKAGE_DIR%"
if errorlevel 1 (
    echo PACKAGE_CONSUMER_SMOKE_RESULT=FAIL
    echo PACKAGE_CONSUMER_SMOKE_FAILED_STAGE=PACKAGE_LAYOUT
    exit /b 1
)

if exist "%CONSUMER_BUILD_DIR%" rmdir /s /q "%CONSUMER_BUILD_DIR%"
if exist "%SOFTWARE_CONSUMER_BUILD_DIR%" rmdir /s /q "%SOFTWARE_CONSUMER_BUILD_DIR%"

set "CONFIGURE_ARGS=-S "%ROOT_DIR%\tests\package_consumer" -B "%CONSUMER_BUILD_DIR%" -DCMAKE_PREFIX_PATH="%PACKAGE_DIR%" -DWHATSCANVAS_PACKAGE_TARGET=OpenGL"
if not "%GENERATOR%"=="" set "CONFIGURE_ARGS=%CONFIGURE_ARGS% -G "%GENERATOR%""
if not "%MAKE_PROGRAM%"=="" set "CONFIGURE_ARGS=%CONFIGURE_ARGS% -DCMAKE_MAKE_PROGRAM="%MAKE_PROGRAM%""
if not "%CXX_COMPILER%"=="" set "CONFIGURE_ARGS=%CONFIGURE_ARGS% -DCMAKE_CXX_COMPILER="%CXX_COMPILER%""
if not "%RC_COMPILER%"=="" set "CONFIGURE_ARGS=%CONFIGURE_ARGS% -DCMAKE_RC_COMPILER="%RC_COMPILER%""
if not "%MT_PROGRAM%"=="" set "CONFIGURE_ARGS=%CONFIGURE_ARGS% -DCMAKE_MT="%MT_PROGRAM%""
if "%GENERATOR_IS_MULTI_CONFIG%"=="0" set "CONFIGURE_ARGS=%CONFIGURE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIG%"

cmake %CONFIGURE_ARGS%
if errorlevel 1 (
    echo PACKAGE_CONSUMER_SMOKE_RESULT=FAIL
    echo PACKAGE_CONSUMER_SMOKE_FAILED_STAGE=CONFIGURE
    exit /b 1
)

cmake --build "%CONSUMER_BUILD_DIR%" --config %CONFIG%
if errorlevel 1 (
    echo PACKAGE_CONSUMER_SMOKE_RESULT=FAIL
    echo PACKAGE_CONSUMER_SMOKE_FAILED_STAGE=BUILD
    exit /b 1
)

set "SOFTWARE_CONFIGURE_ARGS=-S "%ROOT_DIR%\tests\package_consumer" -B "%SOFTWARE_CONSUMER_BUILD_DIR%" -DCMAKE_PREFIX_PATH="%PACKAGE_DIR%" -DWHATSCANVAS_PACKAGE_TARGET=Software"
if not "%GENERATOR%"=="" set "SOFTWARE_CONFIGURE_ARGS=%SOFTWARE_CONFIGURE_ARGS% -G "%GENERATOR%""
if not "%MAKE_PROGRAM%"=="" set "SOFTWARE_CONFIGURE_ARGS=%SOFTWARE_CONFIGURE_ARGS% -DCMAKE_MAKE_PROGRAM="%MAKE_PROGRAM%""
if not "%CXX_COMPILER%"=="" set "SOFTWARE_CONFIGURE_ARGS=%SOFTWARE_CONFIGURE_ARGS% -DCMAKE_CXX_COMPILER="%CXX_COMPILER%""
if not "%RC_COMPILER%"=="" set "SOFTWARE_CONFIGURE_ARGS=%SOFTWARE_CONFIGURE_ARGS% -DCMAKE_RC_COMPILER="%RC_COMPILER%""
if not "%MT_PROGRAM%"=="" set "SOFTWARE_CONFIGURE_ARGS=%SOFTWARE_CONFIGURE_ARGS% -DCMAKE_MT="%MT_PROGRAM%""
if "%GENERATOR_IS_MULTI_CONFIG%"=="0" set "SOFTWARE_CONFIGURE_ARGS=%SOFTWARE_CONFIGURE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIG%"

cmake %SOFTWARE_CONFIGURE_ARGS%
if errorlevel 1 (
    echo PACKAGE_CONSUMER_SMOKE_RESULT=FAIL
    echo PACKAGE_CONSUMER_SMOKE_FAILED_STAGE=SOFTWARE_CONFIGURE
    exit /b 1
)

cmake --build "%SOFTWARE_CONSUMER_BUILD_DIR%" --config %CONFIG%
if errorlevel 1 (
    echo PACKAGE_CONSUMER_SMOKE_RESULT=FAIL
    echo PACKAGE_CONSUMER_SMOKE_FAILED_STAGE=SOFTWARE_BUILD
    exit /b 1
)

echo PACKAGE_CONSUMER_SMOKE_RESULT=PASS
exit /b 0
