#!/bin/sh
set -eu

REPOSITORY_ROOT="$(cd "${PROJECT_DIR}/../.." && pwd)"
TARGET_ARCH="${CURRENT_ARCH:-}"
if [ -z "${TARGET_ARCH}" ] || [ "${TARGET_ARCH}" = "undefined_arch" ]; then
  TARGET_ARCH="${NATIVE_ARCH_ACTUAL:-arm64}"
fi
BUILD_DIRECTORY="${PROJECT_DIR}/build/${PLATFORM_NAME}/${CONFIGURATION}"

cmake -S "${REPOSITORY_ROOT}" -B "${BUILD_DIRECTORY}" \
  -DCMAKE_SYSTEM_NAME=iOS \
  -DCMAKE_OSX_SYSROOT="${SDKROOT}" \
  -DCMAKE_OSX_ARCHITECTURES="${TARGET_ARCH}" \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=15.0 \
  -DCMAKE_BUILD_TYPE="${CONFIGURATION}" \
  -DWHATSCANVAS_BUILD_OPENGL=OFF \
  -DWHATSCANVAS_BUILD_OPENGLES=OFF \
  -DWHATSCANVAS_BUILD_METAL=ON \
  -DWHATSCANVAS_BUILD_SOFTWARE=OFF \
  -DWHATSCANVAS_BUILD_DEMO=OFF \
  -DWHATSCANVAS_BUILD_BENCHMARKS=OFF \
  -DWHATSCANVAS_ENABLE_OPENTYPE_SHAPING=OFF \
  -DWHATSCANVAS_ENABLE_FREETYPE_RASTERIZER=OFF \
  -DWHATSCANVAS_ENABLE_SCRIPT_TESTS=OFF \
  -DWHATSCANVAS_INSTALL=OFF \
  -DBUILD_TESTING=OFF

cmake --build "${BUILD_DIRECTORY}" --target WhatsCanvasMetal --parallel
